name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test (node=${{ matrix.node }},platform=${{ matrix.platform }})

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node:
          - "18"
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Boot up Directus
        run: |
          docker-compose up --wait --wait-timeout 120 -d

      - name: Load schema
        run: |
          ./directus run schema apply .directus/snapshot.yaml

      - name: Make sure Directus is healthy
        run: |
          docker-compose ps
          docker-compose logs
